spring:
  application:
    name: yolo-service
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: ${PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true